### ISSUE TITLE
CSS Inject

### ISSUE THREAD

**Issue by Idered** [hexojs/hexo-browsersync#10]
I've tried this:

```
if(self.route.isModified(path)){
    queue.push(path);
}
```

in [here](https://github.com/hexojs/hexo-browsersync/blob/b0ad136a35992cea1cfbd54a407c3a1c8c446c33/lib/browsersync.js#L25)

but isModified returns that all html files except css file were changed. If we could get this method to work properly, we would also get CSS inject feature working.

Any ideas?

**Comment by tcrowe** [comment]
Yes, old issue, but I tried this in here https://github.com/hexojs/hexo-browsersync/blob/master/lib/browsersync.js#L40 @Idered 

I think that event is firing with multiple changes at once. I tried just doing a CSS reload but I couldn't easily get it working. Maybe we can toy with it if you're still interested and you can PR if it works. Sound good? Can we close it?
