### ISSUE TITLE
Documentation does not say anything how to use this plugin...

### ISSUE THREAD

**Issue by marcinant** [hexojs/hexo-browsersync#12]
I installed this plugin as dependency and.... what next?

With `hexo server` nothing happens. 'Hexo is running at http://localhost:4000' as usual.

What should I do to initialize BrowserSync with `hexo server` ?

Could you please extend **README.md**?

**Comment by seisman** [comment]
Try this
```
npm install -g browser-sync
npm install hexo-browsersync --save
hexo server
```

**Comment by marcinant** [comment]
This is exactly what I did. I don't see BrowserSync up and running. I read code and see that this should inject snippet.... and that's it? Do I need to run BS instance elsewhere?
