### ISSUE TITLE
BrowserSync not works with hexo-renderer-jade

### ISSUE THREAD

**Issue by AbraaoAlves** [hexojs/hexo-browsersync#13]
I love browsersync and use it to make my own theme, but despite nicely works with hexo-renderer-ejs, I dont have same features with hexo-renderer-jade plugin!
#### Feature: _compile, render and reload on change layout jade file._

Here a [repo](https://github.com/AbraaoAlves/hexo-sample) with two branchs: [jade](https://github.com/AbraaoAlves/hexo-sample/tree/jade)(not works) and [ejs](https://github.com/AbraaoAlves/hexo-sample/tree/ejs)(works)

Remember: I only started hexo blog and add/config plugins/themes.

**Comment by AbraaoAlves** [comment]
Note: Re-render only happens on jade files in root layout, different of ejs renderer where change any ejs  partial file starts a re-render.

**Comment by reubano** [comment]
Same issue

**Comment by kirainmoe** [comment]
I have the same problem...

**Comment by Turqueso** [comment]
hexo-renderer-jade is now [hexo-renderer-pug](https://github.com/iwarner/hexo-renderer-pug), jade changed it's name to [pug](https://pugjs.org/api/getting-started.html)

**Comment by Molunerfinn** [comment]
For development, I solved this problem although not perfect.
See [this](https://github.com/hexojs/hexo-renderer-jade/issues/6#issuecomment-321986221).
