### ISSUE TITLE
How do i replace snippet **http://HOST:3000/** to **https://HOST:3000/**

### ISSUE THREAD

**Issue by motcwang** [hexojs/hexo-browsersync#14]
I want to replace http static file server to https. so how to configure?
```
<script id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.js?v=2.17.5'><\/script>".replace("HOST", location.hostname));
//]]></script>

replace script url scheme to https.
```

**Comment by tcrowe** [comment]
Hey @motcwang sorry it took so long to get back with you.

If you still need this you can edit the `_config.yml` with this:

```yaml
browsersync:
  host: '127.0.0.1' # your host or IP here
  port: 4001
```

It will then bind to that host/port.

Recommending closing the issue if we can! Thank you
