### ISSUE TITLE
browsersync support for running in dev mode?

### ISSUE THREAD

**Issue by idcrook** [hexojs/hexo-browsersync#16]
`hexo-browsersync` has to be in dependencies (`devDependencies `does not work) in `package.json` for ` hexo serve` to work

```json
"dependencies": {
    "hexo-browsersync": "^0.2.0",
 //...
},
```

```json
  "devDependencies": {
    "hexo-browsersync": "^0.2.0"
  }
```

I needed to have it in package.json _dependencies_, otherwise I wouldn't get the following notification, nor the code injection in the footer.

```
[BS] Access URLs:
 ----------------------------------
          UI: http://localhost:3001
 ----------------------------------
 UI External: http://10.0.1.16:3001
 ----------------------------------
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/blog/. Press Ctrl+C to stop.
```

**Comment by tcrowe** [comment]
Sorry @idcrook that it took so long to get back to you. What was the solution?
