### ISSUE TITLE
is this supposed to work with hexo: 2.8.3 ?

### ISSUE THREAD

**Issue by gaboesquivel** [hexojs/hexo-browsersync#3]

**Comment by celsomiranda** [comment]
No. `hexo-browsersync` depends on `hexo-server`which is only used in version 3.0.0.

Hexo 2.x.x uses a builtin server which is not compatible with this plugin.

You can however use [hexo-browser-sync](https://github.com/hexojs/hexo-browsersync), which is compatible with the older versions.

**Comment by gaboesquivel** [comment]
Thank @celsomiranda
