### ISSUE TITLE
Copy the following snippet into your website message ?

### ISSUE THREAD

**Issue by gaboesquivel** [hexojs/hexo-browsersync#4]
I'm getting this message when I run `hexo s`  but adding that snippet is not necessary for browser sync to work.

```
Copy the following snippet into your website, just before the closing </body> tag
<script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.2.2.3.js'><\/script>".replace("HOST", location.hostname));
//]]></script>
```

**Comment by tommy351** [comment]
This message is displayed by BrowserSync. I can't control.

**Comment by gaboesquivel** [comment]
I think `debugInfo:false` should work. ref: https://github.com/BrowserSync/browser-sync/issues/97

**Comment by tcrowe** [comment]
`N.B.: logSnippet is disabled by default.` was written into the docs. I think this very old issue can be closed, right @NoahDragon ?

**Comment by NoahDragon** [comment]
@tcrowe Yeah, you are right. Closing the issue.
